version: '3.4'

services:
  app:
    image: bull-getting-started:latest
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file: ./.env
    expose:
      - '${PORT}'
    ports:
      - '${PORT}:${PORT}'
    depends_on:
      - redis
    command: "node_modules/.bin/pm2-runtime start ecosystem.config.js --only server"

  worker:
    image: bull-getting-started:latest
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file: ./.env
    depends_on:
      - redis
    command: "node_modules/.bin/pm2-runtime start ecosystem.config.js --only worker"

  redis:
    image: redis:5-alpine
