version: '3.4'

services:
  app:
    volumes:
      - ./:/home/node/app
      - /home/node/app/node_modules
    ports:
      - '${PORT}:${PORT}'


  worker:
    volumes:
      - ./:/home/node/app
      - /home/node/app/node_modules
